import { motion } from 'motion/react';
import { Clock, ArrowRight } from 'lucide-react';
import DetailsPanel from '../components/DetailsPanel';
import AnimatedButton from '../components/AnimatedButton';

const posts=[
['The Future of Headless eCommerce with Next.js','eCommerce','Sep 12, 2026','8 min read','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80','Exploring how headless architectures are transforming online retail by providing unmatched performance and infinite customization.'],
['Mastering Framer Motion for WebGL Interfaces','Web Development','Aug 28, 2026','6 min read','https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80','A deep dive into connecting React state with Three.js canvases using Framer Motion to create seamless, 60fps animations.'],
['Design Systems: From Figma to Tailwind','UI/UX Design','Jul 15, 2026','10 min read','https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80','How to perfectly translate your design tokens from Figma into a robust, scalable Tailwind configuration for large teams.'],
['Why Core Web Vitals Actually Matter in 2026','Performance','Jun 02, 2026','5 min read','https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=800&q=80','Analyzing the direct correlation between LCP, CLS, INP metrics and conversion rates for high-traffic platforms.']
];

export default function Blog(){return <div className="w-full flex flex-col items-center pb-40"><section className="w-full pt-48 pb-28 px-6 text-center"><span className="text-[var(--neon-cyan)] text-sm font-semibold tracking-widest uppercase">Insights & Resources</span><h1 className="text-5xl md:text-7xl font-bold text-white mt-6">Thoughts on<br/><span className="text-transparent bg-clip-text bg-[var(--neon-gradient)]">Design & Code.</span></h1></section><section className="w-full max-w-7xl px-6 md:px-12"><div className="grid md:grid-cols-2 gap-14">{posts.map(([title,cat,date,time,img,excerpt],i)=><motion.article key={title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="group"><div className="relative aspect-video rounded-3xl overflow-hidden glass-card"><img src={img} alt={title} loading="lazy" className="w-full h-full object-cover opacity-70 group-hover:opacity-90 group-hover:scale-105 transition-all duration-700"/><span className="absolute top-4 left-4 px-3 py-1 rounded-full bg-[rgba(5,15,30,.55)] border border-[var(--border-highlight)] backdrop-blur-md text-white text-xs">{cat}</span></div><div className="pt-6"><div className="flex items-center gap-4 text-xs text-[var(--text-muted)] uppercase tracking-widest"><span>{date}</span><span className="flex items-center gap-1"><Clock className="w-3 h-3 text-[var(--neon-cyan)]"/>{time}</span></div><h3 className="text-2xl md:text-3xl font-bold text-white mt-4 group-hover:text-[var(--neon-cyan)] transition-colors">{title}</h3><p className="text-[var(--text-secondary)] leading-relaxed mt-3">{excerpt}</p><DetailsPanel><div className="space-y-5"><p className="leading-relaxed">{excerpt} This expanded preview explains the practical context, implementation considerations and decisions readers can explore when working on similar digital products.</p><div><h4 className="text-white font-semibold mb-2">Inside this article</h4><p>Key principles, implementation strategy, performance considerations, common pitfalls and practical takeaways for real-world projects.</p></div><AnimatedButton variant="outline" showArrow>Read Article</AnimatedButton></div></DetailsPanel></div></motion.article>)}</div></section></div>}
