import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowRight, Clock, BarChart, BookOpen, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import AnimatedButton from '../components/AnimatedButton';
import { courses } from '../data/courses';
import DetailsPanel from '../components/DetailsPanel';

export default function Courses() {
  const [visibleCount,setVisibleCount]=useState(3); const totalCourses=courses.length;
  return <div className="w-full flex flex-col items-center pb-40">
    <section className="w-full pt-48 pb-28 px-6 md:px-12 flex flex-col items-center text-center"><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} className="max-w-4xl"><span className="text-[var(--neon-cyan)] text-sm font-semibold tracking-widest uppercase mb-6 block">Education</span><h1 className="text-5xl md:text-7xl font-bold text-white mb-8">LEARN. BUILD.<br/><span className="text-transparent bg-clip-text bg-[var(--neon-gradient)]">LEVEL UP.</span></h1><p className="text-xl text-[var(--text-secondary)] font-light max-w-2xl mx-auto leading-relaxed">Practical courses designed to help you build real-world digital skills. Elevate your engineering and design capabilities.</p></motion.div></section>
    <section className="w-full max-w-7xl px-6 md:px-12"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      <AnimatePresence mode="popLayout">{courses.slice(0,visibleCount).map((course,idx)=><motion.article layout key={course.id} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.45,delay:(idx%3)*.06}} className="group glow-box rounded-3xl overflow-hidden h-full flex flex-col">
        <div className="relative h-56 overflow-hidden"><img src={course.image} alt={course.title} loading="lazy" className="w-full h-full object-cover opacity-75 group-hover:opacity-95 group-hover:scale-105 transition-all duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-[#030508]/80 to-transparent"/><span className="absolute top-4 left-4 px-3 py-1 rounded-full bg-[rgba(5,15,30,.55)] backdrop-blur-md border border-[var(--border-highlight)] text-white text-xs font-semibold tracking-widest uppercase">{course.category}</span><span className="absolute top-4 right-4 text-white font-bold">{course.price}</span></div>
        <div className="p-7 flex flex-col flex-grow"><div className="flex gap-4 text-xs text-[var(--text-secondary)] mb-4"><span className="flex gap-1"><BarChart className="w-4 h-4 text-[var(--neon-cyan)]"/>{course.difficulty}</span><span className="flex gap-1"><Clock className="w-4 h-4 text-[var(--neon-cyan)]"/>{course.duration}</span></div><h3 className="text-2xl font-bold text-white mb-3 group-hover:text-[var(--neon-cyan)] transition-colors">{course.title}</h3><p className="text-[var(--text-secondary)] leading-relaxed">{course.description}</p><div className="mt-5 flex flex-wrap gap-2">{course.skills.slice(0,3).map(s=><span key={s} className="px-3 py-1 rounded-full bg-[var(--surface-light)] border border-[var(--border)] text-xs text-[var(--text-secondary)]">{s}</span>)}</div>
          <DetailsPanel><div className="space-y-7"><p className="leading-relaxed">{course.longDescription}</p><div><h4 className="text-white font-semibold mb-3">What you'll learn</h4><div className="space-y-2">{course.learningOutcomes.map(o=><div key={o} className="flex gap-2"><CheckCircle2 className="w-4 h-4 text-[var(--neon-cyan)] mt-1 shrink-0"/><span>{o}</span></div>)}</div></div><div><h4 className="text-white font-semibold mb-3">Curriculum</h4><div className="space-y-2">{course.curriculum.map(m=><div key={m.module} className="flex justify-between gap-4 border-b border-[var(--border)] pb-2"><span>{m.title}</span><span className="text-xs">{m.lessons} lessons</span></div>)}</div></div><div><h4 className="text-white font-semibold mb-2">Requirements & audience</h4><p>{course.requirements.join(' • ')}</p><p className="mt-2">For: {course.audience.join(', ')}</p></div><Link to={`/courses/${course.slug}`} className="inline-flex items-center gap-2 text-white hover:text-[var(--neon-cyan)] font-semibold">START LEARNING <ArrowRight className="w-4 h-4"/></Link></div></DetailsPanel>
        </div>
      </motion.article>)}</AnimatePresence></div>
      {totalCourses>3&&<div className="mt-16 flex justify-center"><AnimatedButton variant="outline" onClick={()=>setVisibleCount(visibleCount<totalCourses?totalCourses:3)} showArrow={false}>{visibleCount<totalCourses?'View More Courses ↓':'Show Less ↑'}</AnimatedButton></div>}
    </section>
  </div>;
}
