import { motion, useScroll, useTransform } from 'motion/react';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { projects } from '../data/projects';
import { services } from '../data/services';
import AnimatedButton from '../components/AnimatedButton';
import DetailsPanel from '../components/DetailsPanel';

export default function Home() {
  const { scrollY } = useScroll(); const y1 = useTransform(scrollY,[0,1000],[0,120]);
  return <div className="w-full flex flex-col items-center">
    <section className="relative w-full min-h-screen flex items-center justify-center px-6 md:px-12 pt-24 pb-12"><motion.div style={{y:y1}} className="max-w-4xl w-full text-center z-10"><motion.div initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="inline-flex items-center gap-2 mb-7 px-4 py-2 rounded-full border border-[var(--border)] bg-[var(--surface)] backdrop-blur-md"><span className="w-2 h-2 rounded-full bg-[var(--neon-cyan)] shadow-[0_0_8px_var(--neon-cyan)]"/><span className="text-xs font-semibold tracking-wider text-zinc-300 uppercase">Available for new projects</span></div><h1 className="text-5xl md:text-7xl font-bold text-white mb-6 leading-[1.1]">BUILDING DIGITAL<br/><span className="text-transparent bg-clip-text bg-[var(--neon-gradient)]">EXPERIENCES</span> THAT MOVE PEOPLE.</h1><p className="text-lg md:text-xl text-[var(--text-secondary)] mb-10 leading-relaxed max-w-2xl mx-auto font-light">I design and build modern digital experiences, high-performance websites, eCommerce solutions, and practical learning experiences for businesses and ambitious creators.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-6"><AnimatedButton to="/projects" variant="primary">Explore My Work</AnimatedButton><AnimatedButton to="/contact" variant="outline" showArrow={false}>Let's Work Together</AnimatedButton></div></motion.div></motion.div></section>
    <section className="w-full py-36 px-6 md:px-12 border-y border-[var(--border)] relative"><div className="max-w-7xl mx-auto"><div className="mb-16"><span className="text-[var(--neon-cyan)] text-sm font-semibold tracking-widest uppercase">Capabilities</span><h2 className="text-4xl md:text-5xl font-bold text-white mt-4">A focused toolkit for<br/>digital growth.</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-7">{services.map((service,idx)=><motion.article key={service.id} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:idx*.05}} className="glass-card p-7 group"><span className="text-sm text-[var(--text-muted)] font-mono">{service.id}</span><h3 className="text-xl font-bold text-white mt-5 group-hover:text-[var(--neon-cyan)] transition-colors">{service.title}</h3><p className="text-[var(--text-secondary)] leading-relaxed mt-3">{service.description}</p><DetailsPanel><div className="space-y-3"><h4 className="text-white font-semibold">Included</h4>{service.includes.map(item=><div key={item} className="flex gap-2"><CheckCircle2 className="w-4 h-4 text-[var(--neon-cyan)] mt-1"/><span>{item}</span></div>)}<Link to="/contact" className="inline-flex items-center gap-2 mt-3 text-white hover:text-[var(--neon-cyan)] font-semibold">REQUEST SERVICE <ArrowRight className="w-4 h-4"/></Link></div></DetailsPanel></motion.article>)}</div></div></section>
    <section className="w-full py-36 px-6 md:px-12"><div className="max-w-7xl mx-auto"><div className="flex justify-between items-end mb-16"><div><span className="text-[var(--neon-cyan)] text-sm font-semibold tracking-widest uppercase">Selected Work</span><h2 className="text-4xl md:text-5xl font-bold text-white mt-4">Recent projects.</h2></div><Link to="/projects" className="hidden md:flex items-center gap-2 text-[var(--text-secondary)] hover:text-white">All projects <ArrowRight className="w-4 h-4"/></Link></div><div className="grid md:grid-cols-2 gap-10">{projects.map((project,idx)=><motion.article key={project.id} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="group"><div className="relative aspect-[16/10] rounded-3xl overflow-hidden glass-card"><img src={project.image} alt={project.title} loading="lazy" className="w-full h-full object-cover opacity-70 group-hover:opacity-90 group-hover:scale-105 transition-all duration-700"/></div><div className="pt-6"><span className="text-xs text-[var(--neon-cyan)] uppercase tracking-widest">{project.category}</span><h3 className="text-2xl font-bold text-white mt-2">{project.title}</h3><p className="text-[var(--text-secondary)] mt-2">{project.description}</p><DetailsPanel><p className="leading-relaxed">Explore the implementation, technology choices and product focus behind this project. The experience was shaped around performance, usability and a strong visual system.</p><div className="flex flex-wrap gap-2 mt-5">{project.technologies.map(t=><span key={t} className="px-3 py-1 rounded-full bg-[var(--surface-light)] border border-[var(--border)] text-xs">{t}</span>)}</div></DetailsPanel></div></motion.article>)}</div><div className="mt-20 text-center"><AnimatedButton to="/projects" variant="outline">View All Projects</AnimatedButton></div></div></section>
    <section className="w-full py-40 px-6 md:px-12 border-t border-[var(--border)]"><div className="max-w-4xl mx-auto text-center"><h2 className="text-5xl md:text-7xl font-black text-white mb-8">READY TO START<br/>YOUR NEXT PROJECT?</h2><p className="text-xl text-[var(--text-secondary)] mb-12 font-light">Have an idea, project, business or learning goal? Let's turn it into something real.</p><AnimatedButton to="/contact" variant="primary">Let's Build Together</AnimatedButton></div></section>
  </div>;
}
